import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
	keywords: ['justwatch', 'animes', 'movie', 'movies'],
};

export default async function Home() {
	return <div>Home</div>;
}
