import type { Metadata } from 'next';
import '@/public/assets/fonts/SanFrancisco/index.css';
import '@/public/assets/styles/static.css';
import '@/public/assets/styles/typography.css';
import './globals.css';
export const metadata: Metadata = {
	icons: '/assets/icons/logo.svg',
	title: 'JustWatch',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en' className='dark'>
			<body>{children}</body>
		</html>
	);
}
