import type { Metadata } from 'next';
import '@/public/assets/fonts/SanFrancisco/index.css';
import '@/public/assets/styles/static.css';
import '@/public/assets/styles/typography.css';
import './globals.css';
import Navbar from '@components/layout/navbar';
import { ThemeProvider } from './provider';

export const metadata: Metadata = {
	icons: '/assets/icons/logo.svg',
	title: 'JustWatch',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false} disableTransitionOnChange>
					<Navbar />
					<main className='*:not-[.profile]:pt-27'>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
