import { getBaseUrl } from '@/miscs/getBaseUrl';
import { cookieHeader } from '@/miscs/getCookies';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
	keywords: ['justwatch', 'animes', 'movie', 'movies'],
};

export default async function Home() {
	const res = await fetch(`${getBaseUrl()}/api/account/profile`, { method: 'GET', headers: { cookie: cookieHeader } });
	const data = (await res.json()).data as { firstname: string; lastname: string; username: string };

	return <div>Home</div>;
}
